name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
    - name: Init Capacitor project
      run: |
        npm init -y
        npx cap init LiveTVApp com.example.livetv
        npx cap add android
        cp -r ./ ./android/app/src/main/assets/public
        npx cap copy
        echo "APK tayari kwa build (Android Studio required kwa release)"
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: app-files
        path: ./android
